name: Run CI checks

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master, dev]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.15
    with:
      main-branch-name: 'master'
      parallel-commands: |
        npx nx-cloud record npx nx format:check
        npx nx-cloud record yarn documentation:check --verbose
      parallel-commands-on-agents: |
        yarn nx affected --target lint build test e2e

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.15
    with:
      number-of-agents: 3
