name: Run PR checks

on: pull_request

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

# TODO: Figure out why DTE is not handling demo app well.
# It appears that the task graph on the DTE side doesn't
# contain the relationship between the demo webapi and the
# demo models library. This causes the C# build to fail.

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.15
    with:
      main-branch-name: 'master'
      parallel-commands: |
        npx nx-cloud record yarn nx format:check
        npx nx-cloud record yarn documentation:check --verbose
        npx nx-cloud record yarn commitlint --from ${{ github.event.pull_request.base.sha }} --to HEAD --verbose
      parallel-commands-on-agents: |
        yarn nx affected --target lint build test e2e

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.15
    with:
      number-of-agents: 3
